### ISSUE TITLE
Runtime error on trainng

### ISSUE THREAD

**Issue by sbmaruf** [facebookresearch/MUSE#18]
While training embedding with `unsupervised.py` by the changing 
default flag `--dis_most_frequent 75000`  to  `--dis_most_frequent 99999` I got the following error,

```
Traceback (most recent call last):
  File "unsupervised.py", line 135, in <module>
    evaluator.all_eval(to_log)
  File "/data/sls/qcri/asr/sjoty/sbmaruf/MUSE/MUSE/src/evaluation/evaluator.py", line 192, in all_eval
    self.dist_mean_cosine(to_log)
  File "/data/sls/qcri/asr/sjoty/sbmaruf/MUSE/MUSE/src/evaluation/evaluator.py", line 173, in dist_mean_cosine
    t2s_candidates = get_candidates(tgt_emb, src_emb, _params)
  File "/data/sls/qcri/asr/sjoty/sbmaruf/MUSE/MUSE/src/dico_builder.py", line 125, in get_candidates
    all_scores = all_scores[:params.dico_max_size]
RuntimeError: invalid argument 2: dimension 0 out of range of 0D tensor at /opt/conda/conda-bld/pytorch_1512386481460/work/torch/lib/TH/generic/THTensor.c:24
```

**Comment by glample** [comment]
What are the sizes of the source and target vocabularies?

**Comment by sbmaruf** [comment]
> source-en: 243003, 
> target-es: 872827.
> min_vocab = 200000

**Comment by glample** [comment]
Okay it looks like the built dictionary is empty.
This is possible if you have `dico_build` set to `S2T&T2S`, it means that there is no reciprocity in the nearest neighbors at all (if x is translation of y then y is not translation of x). This happens when the alignment is very bad, and that the model failed to make a good initial alignment. The reason for that can be that:
- you did not train the model long enough and it did not have time to align the emebddings
- the embeddings are too hard to align and the model just can't find a way to align it

You can avoid this issue by defining `dico_build` to `S2T`. This should fix the bug, but the model still might not converge.

**Comment by sbmaruf** [comment]
Thanks for the help. @glample
