### ISSUE TITLE
Assertion Error in unsupervised training

### ISSUE THREAD

**Issue by berzentine** [facebookresearch/MUSE#28]
`INFO - 03/01/18 16:49:10 - 0:00:00 - The experiment will be stored in /usr2/home/nkvyas/Bayesian/MUSE/dumped/6uymzfdoug
Traceback (most recent call last):
  File "unsupervised.py", line 91, in <module>
    src_emb, tgt_emb, mapping, discriminator = build_model(params, True)
  File "/usr2/home/nkvyas/Bayesian/MUSE/src/models.py", line 46, in build_model
    src_dico, _src_emb = load_external_embeddings(params, source=True)
  File "/usr2/home/nkvyas/Bayesian/MUSE/src/utils.py", line 282, in load_external_embeddings
    assert len(split) == 2
AssertionError`

**Comment by Janinanu** [comment]
I get the same error. How did you solve it?

**Comment by glample** [comment]
Usually word embedding files have a first line which is composed of 2 integers: the number of word embeddings, and the dimension of the embeddings. This part in the codes tries to recover these 2 values:
https://github.com/facebookresearch/MUSE/blob/master/src/utils.py#L277-L280

If your embedding file doesn't start with this special line, you can either add it manually to your file, or do something a bit hacky like replacing the `if i == 0` by `if i == -1` so that the code ignores this part.

**Comment by Janinanu** [comment]
Thanks for the hint! However, in my case, the error occurs when I try to run the code following the instructions from the README: 
`python unsupervised.py --src_lang en --tgt_lang es --src_emb data/wiki.en.vec --tgt_emb data/wiki.es.vec --n_refinement 5` 
using the data downloaded with 
`curl -Lo data/wiki.en.vec https://dl.fbaipublicfiles.com/fasttext/vectors-wiki/wiki.en.vec
`
and 
`curl -Lo data/wiki.es.vec https://dl.fbaipublicfiles.com/fasttext/vectors-wiki/wiki.es.vec
`

**Comment by glample** [comment]
Mmm this is weird. Can you show the first line of these 2 embedding files?

**Comment by dipen-yadav** [comment]
I was facing the same problem. As @glample replied, the problem was with the embeddings files. My both Spanish and English embedding files somehow didn't download properly. Once, I put the correct embedding file, it worked.
