### ISSUE TITLE
CSLS calculation understanding

### ISSUE THREAD

**Issue by sufengniu** [facebookresearch/MUSE#45]
Hello, in the paper CSLS is calculated by the following equation 
![image](https://user-images.githubusercontent.com/2965176/39271131-1b8a7db8-48a6-11e8-93cb-9072776d097f.png)
since three terms are all pairwise cosine similarity (or mean k nearest neighbor similarity), each tensor should be size as [dictionary_size, 1]. However when I look at the [code ](https://github.com/facebookresearch/MUSE/blob/master/src/dico_builder.py#L87), I found that cos(Wx,y) size as [128*dictionary_size], and `average_dist1[i:min(n_src, i + bs)][:, None] + average_dist2[None, :]` also sizes as [128*dictionary_size]. I wonder what is this 128 means, or if I misunderstand any details? Thank you!

**Comment by glample** [comment]
Hi,

The `128` here is just the batch size. For `128` source words we look at their best translations over all target words. We do that batch by batch because otherwise it involves to create a matrix of size `(n_src, n_tgt)` in memory (where `n_src` and `n_tgt` are the numbers of source and target words) and this will not fit for large vocabularies.

**Comment by sufengniu** [comment]
I see. that makes sense. In that case, I wonder what is the reason to pickup the top 2 best scores, I mean to make candidate pairs, top 1 and its self should work already. Thank you!

**Comment by glample** [comment]
Because there is an option `dico_threshold` that looks at the difference between the score of the best and second best translation, and will only take translation pairs where this difference is above the threshold, i.e. there is no ambiguity and the best translation is clearly better than the second best. For this we need to select the best 2 scores, i.e. we concat all top2 words from each batch :)

But this is just an option which we do not use in practice.

**Comment by sufengniu** [comment]
I see. Thank you for elaboration!
