### ISSUE TITLE
TypeError when using cuda

### ISSUE THREAD

**Issue by prabhakar267** [facebookresearch/MUSE#51]
When trying with cuda set to true, i am getting this error  on [supervised.py#L103](https://github.com/facebookresearch/MUSE/blob/master/supervised.py#L103)
```
TypeError: tensor(0.5628, device='cuda:0') is not JSON serializable
```

**Comment by glample** [comment]
Which version of PyTorch are you using?

**Comment by sakshimaskara07** [comment]
I am getting the same error with cuda set to false
TypeError: tensor(0.6204) is not JSON serializable

Traceback (most recent call last):
  File "supervised.py", line 93, in <module>
    logger.info("__log__:%s" % json.dumps(to_log))
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")

**Comment by glample** [comment]
This is most likely due to the last version of PyTorch -- many changes appeared in the version 0.4.0 (actually I'm quite surprised the script did not fail before line 93).

Looking at the error it looks like there is something in `to_log` which is a PyTorch object (maybe a scalar Tensor, as opposed to a float with PyTorch 0.3), and `json` does not know how to serialize this. If this is the issue then this should be a simple fix. Can you print everything in `to_log` and copy-paste it here? My guess is that there is a Torch tensor somewhere that should just be a Python scalar. This https://discuss.pytorch.org/t/get-value-out-of-torch-cuda-float-tensor/2539/7 might also be relevant (post is outdated, but the issue would be similar).

I don't have time to look more into this now, but we will push a fix next week.
