### ISSUE TITLE
How to keep the upper-case words?

### ISSUE THREAD

**Issue by bdqnghi** [facebookresearch/MUSE#59]
After the training steps, all of the words are in lower case, how can i keep them as the original version?

**Comment by glample** [comment]
The words are lowercased so that they can be evaluated, but the export function will take care of uppercased and lowercased words. If you see this: https://github.com/facebookresearch/MUSE/blob/master/src/utils.py#L264
when the full vocabulary is loaded (at the experiment, when exporting aligned embeddings), then the words casing is not changed.
